user www-data;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        #SSL/TLS configuration
        listen 443 ssl;
        server_name cecompte.42.fr;

        ssl_certificate     /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        #root and index (default file)
        root /var/www/html;
        index index.php;
        
        # Fallback if requested URL is not an actual file or directory
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # pass PHP scripts on Nginx to FastCGI (PHP-FPM) server
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
        }
    }
}