services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp-data:/var/www/html
    ports:
      - "8080:443"
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp-data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cecompte/data/mariadb
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/cecompte/data/wordpress

networks:
  inception:
    driver: bridge


# to do : 
# - secrets management : https://docs.docker.com/compose/how-tos/use-secrets/
# - wordpress 2 users
# - install on VM
# - Both named volumes must store their data inside /home/login/data 
# on the host machine. Replace "login" with your learner’s username. No bind mounts.
# - must create the /home/cecompte/data/mariadb and /home/cecompte/data/wordpress on host machine\
