services:
  nginx:
    container_name: nginx
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME=}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      -"3306:3306"
    volumes:
      -dbdata:/var/lib/mysql


volumes:
  db-data: