services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp-data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp-data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  db-data:
  wp-data:

networks:
  inception:
    driver: bridge